### ISSUE TITLE
Crashing with waifu2x-converter-cpp versions newer than 5.2 - "couldn't open noise0_model.json"

### ISSUE THREAD

**Issue by NintendoManiac64** [maz-1/waifu2x-gui#2]
Simply put, version 5.2 was the last version of waifu2x-converter-cpp that worked with this program, but it has since moved on to version 5.2.2 which, when the command line output is enabled, gives the following error:

couldn't open noise0_model.json

**Comment by maz-1** [comment]
you need to update models as well.
